<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Резюме',
    'Action Buttons' => 'Кнопки действий',
    'Are you sure you want to delete this item?' => 'Вы уверены, что желаете удалить эту запись?',
    'Author' => 'Автор',
    'Book Publish Date' => 'Дата выхода книги',
    'Books' => 'Книги',
    'Contact' => 'Контакты',
    'Create' => 'Создать',
    'Create Book' => 'Создать книгу',
    'Created at' => 'Дата добавления',
    'Delete' => 'Удалить',
    'Email' => '',
    'First name' => 'Имя',
    'Home' => 'Главная страница',
    'ID' => '',
    'If you forgot your password you can {reset} it.' => 'Если Вы забыли пароль, его можно {reset}.',
    'Last name' => 'Фамилия',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Name' => 'Название',
    'Password' => 'Пароль',
    'Please choose your new password:' => 'Придумайте новый пароль:',
    'Please fill out the following fields to login:' => 'Для входа на сайт заполните следующие поля:',
    'Please fill out the following fields to signup:' => 'Для регистрации на сайте заполните следующие поля:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Укажите ваш email.'
        . 'На этот адрес придет ссылка для восстановления пароля.',
    'Preview' => 'Превью',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Запрос на восстановление пароля',
    'Reset password' => 'Восстановление пароля',
    'Save' => 'Сохранить',
    'Search' => 'Искать',
    'Send' => 'Отправить',
    'Sergey Cherdantsev' => 'Сергей Черданцев',
    'Signup' => 'Регистрация',
    'This email address has already been taken.' => 'Указанный email уже занят.',
    'This username has already been taken.' => 'Указанное имя пользователя уже занято.',
    'Until' => 'До',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => 'Редактировать {modelClass}:',
    'Updated at' => 'Дата обновления',
    'User Name' => 'Имя пользователя',
    '[delete]' => '[удл]',
    '[update]' => '[ред]',
    '[view]' => '[просм]',
    'reset' => 'восстановить',
];
